export default {
    DEFAULT_SOURCE_DIR: '/assets/',
    BOX_WIDTH: 400,
    BOX_HEIGHT: 300,
    DEFAULT_WIDTH: 800,
    DEFAULT_HEIGHT: 600,
    DEFAULT_SECTION: 65,
    DEFAULT_ITEM_WIDTH: 48,
    DEFAULT_ITEM_HEIGHT: 64.5,
    SCALE: 1
}