export default {
    DEFAULT_SOURCE_DIR: '/assets/',
    BOX_WIDTH: 800,
    BOX_HEIGHT: 600,
    DEFAULT_WIDTH: 800,
    DEFAULT_HEIGHT: 600,
    DEFAULT_SECTION: 65,
    DEFAULT_ANIMATION_STEP: 50,
    DEFAULT_MOVE_SECTION_TIMES: 0.3,
    SCALE: 1
}